### ISSUE TITLE
Can't find kvs.pb.h in repository

### ISSUE THREAD

**Issue by bsnote** [hydro-project/fluent#136]
There is this include statement in _common.hpp_ for example:

`#include "kvs.pb.h"`

but the _kvs.pb.h_ file cannot be found in repository.

**Comment by cw75** [comment]
Hi @bsnote ,

Files with suffix `.pb.h` are protobuf generated files that will be auto-generated during the compilation.

**Comment by bsnote** [comment]
Hi @cw75,
Thanks for clarifying that! Closing the issue...
